### ISSUE TITLE
Total number of listings/communities

### ISSUE THREAD

**Issue by vasdhara** [mhbo/mhbo-js#15]
Need an API call to get the total number of results for each search. This will be required in the client to show the user, also it would help in allowing the client to set up live server-side pagination by automatically calculating the number of page calls possible.

**Comment by vasdhara** [comment]
Also, for state-wise search, an API call to get the total number of listings for each city in the state, along with the list of cities.

**Comment by vasdhara** [comment]
and the total number of communities for the same

**Comment by housing** [comment]
@vasdhara We are we with this? Has this issue been resolved for you yet?

**Comment by vasdhara** [comment]
No, haven't got an update on this so far.

**Comment by vasdhara** [comment]
@jeremy-loss @housing The reason for this issue was the different design of listings sidebar for a state search, is that design still to be implemented? Else this issue can be closed.

**Comment by housing** [comment]
Yes there is a different design, but we'll close this one. I will review this with Kelly next week and setup a new task.
