### ISSUE TITLE
Get SEO Text for a search

### ISSUE THREAD

**Issue by vasdhara** [mhbo/mhbo-js#18]
An API call to get the SEO data for each search to be displayed below the listings

**Comment by housing** [comment]
@vasdhara - I will be tasking one of our developers with fixing the markdown tool in admin - as well making sure we can make the api to fetch the copy.

**Comment by vasdhara** [comment]
@jeremy-loss @housing as per discussion in slack, this is no longer a required feature? Shall I close this issue?

**Comment by jeremy-loss** [comment]
@vasdhara - you can close this out. Peter might have other plans to add more information, but they won't be related to this specific SEO request.
