### ISSUE TITLE
Fields missing from communities

### ISSUE THREAD

**Issue by vasdhara** [mhbo/mhbo-js#28]
number of homes for sale and rent
age restricted and what age

**Comment by jeremy-loss** [comment]
These are the new fields I am proposing the API return:
   age_restriction_type: number
   mobilehomes: [IMHBOListing]

**Comment by jeremy-loss** [comment]
@vasdhara I have added these fields in the detail results. I will assign this issue to you to add these fields into the API itself with a new address type, something like ILatLonAddress.
Here is an example of the added fields - https://staging.mhbo.com/api/v1/communities/38914

**Comment by vasdhara** [comment]
@jeremy-loss 
The example linked above returns age_restriction_type: null. 
What does this correspond to? All - Ages?

**Comment by jeremy-loss** [comment]
> @jeremy-loss
> The example linked above returns age_restriction_type: null.
> What does this correspond to? All - Ages?

I think we have to account for a possible null value and not display anything.
