### ISSUE TITLE
Add fields - dealer contact and home square footage

### ISSUE THREAD

**Issue by vasdhara** [mhbo/mhbo-js#31]

**Comment by jeremy-loss** [comment]
@vasdhara - The server is now returning this data. Can you add the types to the API? The contact field names are a little weird, but I am trying to keep them consistent with the backend to make it easier when we start doing updates through the API.

New fields:
mobilehome {
   total_footage: number
}

community:{
   contact : {
       name: string
       last_name: string,
       daytime_phone: string
   }
}

Examples:
https://staging.mhbo.com/api/v1/communities/37475
https://staging.mhbo.com/api/v1/mobile_homes/336023
