### ISSUE TITLE
Add Option to Supply JWT Token

### ISSUE THREAD

**Issue by jeremy-loss** [mhbo/mhbo-js#42]
There needs to be an option to create an MHBO client with an existing JWT token instead of supplying the secret key to generate one. JWT tokens will be available to the React app through cookies and this modification will allow us to use those.

I was thinking we could overload the MHBO constructor to allow for instantiation with a JWT token and an Environment. The client should be able to handle a null or blank token without failing(however we want to handle non-logged in users that don't have a token). The server-side API will return an error if the specific request cannot be made without a token. 

```
Client(
  jwtToken: string,
  environment?: IEnvironment
)
```
The simplest thing to do might be to just add the token as a possible value in ICredentials and if it is present just return it and if not try the secret key. We will probably remove the secret key option at some point in the near future, but we can keep it for now.

**Comment by vasdhara** [comment]
Typescript won't support function overloading with different number of parameters. 
One option would be to modify the function to be 
```
Client(
    credentials: ICredentials,
    environment?: IEnvironment
)
```

and `ICredentials` to be 
```
interface ICredentials {
  apiAccessKey?: string
  apiSecret?: string
  token?: string
}
```

and `requestGet()` under `entityRequest` to call the API by
```
authenticatedRequest(
    creds.token?creds.token:token(creds),
    "GET",
    url,
    environment,
    fetchExecutor
  )
```


How do I test the implementation of token in wrapper before creating a PR, is there anyway to generate a valid token ?

**Comment by jeremy-loss** [comment]
I'm surprised typescript doesn't allow typical overloading, but passing I like passing in an ICredentials object, so that's fine. 

Can you export a new method exposing the token generation and use that for testing? Testing a little hard because it appears we are neither validating nor using the tokens at all on the server. This might change soon, but at he moment it will be pretty hard to tell when a token isn't valid or present.
